### PR TITLE
SuccessHttpStatusCodes option in app.config

### PR DESCRIPTION
**Pull request by mgroves**
Hello, I saw your project on up-for-grabs.net, and I had some spare time, so I implemented the feature you asked for in issue #7 

It uses a very simple wildcard system to meet your requirements. I've tried to document it well, and I added a bunch of unit tests.

I also fixed a few typos in class names and file names while I was in there.

Hope this is useful for you! Thanks for contributing to the C# OSS community.

### CODE REVIEW

**Comment by hmol** [comment]
Great work! :grinning: I really like the way you have implemented all the different tests, I think I just learned something :+1: I also learned how to spell the word "success" correctly :clap:

I'm not sure, but maybe running all the code in the `IsSuccess()` method after each Http request can be a performance issue (parsing the string from app.config and trying to find match with the returned Http-status code)?
Do you think there is a way to make this better, performance wise?
Just a suggestion, but one possible way to do this could be to calculate all the valid status codes (just one time at start up) and put them in a list. `List<int> ValidStatusCodeList { get; set; }`
Then: to check if a Http-request was valid, it would be sufficient to do: `ValidStatusCodeList.Contains(statusCode))`

What do you think? Is it worth it?

**Comment by mgroves** [comment]
**Short answer**: I don't think it makes much difference, but it's easy to check if you're concerned.

**Longer answer**:

I suspect that, compared to the HTTP request, the time to parse the config string is pretty insignificant. If you're really concerned, I would recommend setting up a Stopwatch in both versions and comparing. And since your use case is typically to run it continuously (and update Slack, which I think is pretty darn cool, by the way :smile:), then I think it's even less significant.

Your idea to preload all the codes is one that I would have pursued, except for the wildcard calculations.

However, if you find that performance is affected significantly, then _some_ preloading could be done, but I think you'd still be left with RegEx checks in order to handle the wildcards (or enumerating every possible code from the wildcards). Note that my algorithm is checking the easiest cases first, and won't even do the RegEx unless it needs to. So, for instance, it _might_ be more performant to enumerate: "400, 401, 403, 404" than use wildcard: "40x".

But again, I think we're talking a few ticks, and not a significant amount of processing time compared to HTTP requests, which could easily take 1+ second(s) each.

**Comment by mgroves** [comment]
Ooh, another thing I just noticed was the badly named test method: Will_match_a_single_code_exactly. I should have called that something different after I decided to use TestCase :frowning:

**Comment by hmol** [comment]
@mgroves not concerned, I agree with you, I dont think it will have that big of an impact on the performance. Maybe I will look into it sometime, but I think it works great now as well :)
Pull request merged, thanks for contributing to my little repo here :neckbeard:
Any suggestions to other improvements/possible additions of functionality is welcome :smiley:

**Comment by hmol** [comment]
The testcase name is nothing to worry about, I understood what you meant.

**Pull request merged**
